apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-container
  template:
    metadata:
      labels:
        app: gateway-container
    spec:
      containers:
      - name: gateway-container
        image: maalami/springbootgateway
        ports:
        - containerPort: 8442
      nodeSelector:
        role: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-container
  ports:
    - port: 8442
      targetPort: 8442
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: http://localhost:8442
    http:
      paths:
      - path: /store
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 8442
      - path: /inventory
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 8442
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 8442
              
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: gateway-container
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: gateway-container
#  template:
#    metadata:
#      labels:
#        app: gateway-container
#    spec:
#      containers:
#      - name: gateway-container
#        image: maalami/springbootgateway
#        ports:
#        - containerPort: 8442
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: gateway-service
#spec:
#  selector:
#    app: gateway-container
#  ports:
#    - port: 8442
#      targetPort: 8442
#  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: gateway-ingress
#  annotations:
#    kubernetes.io/ingress.class: "gce"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /store
#        pathType: Prefix
#        backend:
#          service:
#            name: gateway-service
#            port:
#              number: 8442